name: route53-action
description: Create a record in Route53 hosted zone
runs:
  using: "node12"
  main: "index.js"
inputs:
  hosted-zone-id:
    description: "Hosted zone id"
    required: true
  comment:
    description: "Comment"
    required: false
  action:
    description: "Action (CREATE/DELETE)"
    required: true
    default: "CREATE"
  resource-record-set:
    description: "Resource record set"
    required: true
